apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube-metrics-collector
  namespace: kube-system
  labels:
    app: kube-metrics-collector
spec:
  template:
    metadata:
      labels:
        name: kube-metrics-collector
        vmi.prometheus.kubevirt.io: ""
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9091"
    spec:
      serviceAccountName: kubevirt-privileged
      hostPID: true
      nodeSelector:
        kubevirt.io/schedulable: "true"
      containers:
      - name: collector
        ports:
        - containerPort: 9091
          protocol: "TCP"
          name: "metrics-vmi"
        image: fromanirh/kube-metrics-collector:v0.10.1
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: kube-metrics-config
          mountPath: /etc/kube-metrics-collector
        - name: cri-runtime
          mountPath: /var/run/dockershim.sock
        env:
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      volumes:
      - name: kube-metrics-config
        configMap:
          name: kube-metrics-config
          items:
          - key: collector.conf
            path: config.json
      - name: cri-runtime
        hostPath:
          path: /var/run/dockershim.sock
